TABLE_(SESSION)
	STRING_ (SID, 32)       PRIMARY_KEY
	BLOB_   (SDATA)
	TIME_   (STIME)
END_TABLE

TABLE_(CLIENT)
	INT_    (ID)            PRIMARY_KEY AUTO_INCREMENT
	STRING_ (NAME, 200)     NOT_NULL UNIQUE
	STRING_ (PASSWORD, 36)  NOT_NULL
	STRING_ (DESCR, 1024)   NOT_NULL
	STRING_ (SRC, 1024)     NOT_NULL
	TIME_   (LAST_ACTIVITY)
	TIME_   (LAST_WORK)     INDEX
	STRING_ (SALT, 4)
	INT_    (MAX_AGE)
	STRING_ (BRANCHES, 1024) NOT_NULL SQLDEFAULT("*")
END_TABLE

TABLE_(AUTH)
	INT_    (AUTH_ID)       PRIMARY_KEY AUTO_INCREMENT
	STRING_ (NONCE, 32)     NOT_NULL
	TIME_   (VALID)         NOT_NULL
END_TABLE

TABLE_(COMMITS)
	STRING_ (UID, 512)      UNIQUE NOT_NULL
	STRING_ (BRANCH, 512)   NOT_NULL SQLDEFAULT("")
	STRING_ (CMT, 512)      NOT_NULL
	TIME_   (DT)            NOT_NULL
	STRING_ (AUTHOR, 200)   NOT_NULL
	STRING_ (MSG, 1024)     NOT_NULL SQLDEFAULT("")
	STRING_ (PATH, 1024)    NOT_NULL
END_TABLE

TABLE_(RESULT)
	STRING_ (CMT_UID, 512)  INDEX NOT_NULL
	INT_    (CLIENT_ID)     INDEX NOT_NULL DUAL_UNIQUE(CMT_UID, CLIENT_ID)
	TIME_   (START)         INDEX NOT_NULL
	TIME_   (FINISHED)
	INT_    (STATUS)        NOT_NULL SQLDEFAULT(0)
	INT_    (OK)            NOT_NULL SQLDEFAULT(0)
	INT_    (ERR)           NOT_NULL SQLDEFAULT(0)
	INT_    (FAIL)          NOT_NULL SQLDEFAULT(0)
	INT_    (SKIP)          NOT_NULL SQLDEFAULT(0)
END_TABLE

TABLE_(MAIL)
	STRING_ (EMAIL, 1024)   NOT_NULL
	STRING_ (FILTER, 1024)  NOT_NULL
	STRING_ (TOKEN, 32)     NOT_NULL
	INT_    (UNIQ)          NOT_NULL UNIQUE
	TIME_   (CTIME)         NOT_NULL
	BOOL_   (ACTIVE)        NOT_NULL SQLDEFAULT(0)
END_TABLE