TABLE_(SESSION)
	STRING_ (SID, 32)       PRIMARY_KEY
	BLOB_   (SDATA)
	TIME_   (STIME)
END_TABLE

TABLE_(CLIENT)
	INT_    (ID)            PRIMARY_KEY AUTO_INCREMENT
	STRING_ (NAME, 200)     UNIQUE
	STRING_ (PASSWORD, 36)
	STRING_ (DESCR, 1024)
	STRING_ (SRC, 1024)
	TIME_   (LAST_ACTIVITY)
	TIME_   (LAST_WORK)     INDEX
	STRING_ (SALT, 4)
	INT_    (MAX_AGE)       SQLDEFAULT(14)
	STRING_ (BRANCHES, 1024) SQLDEFAULT("*")
END_TABLE

TABLE_(AUTH)
	INT_    (AUTH_ID)       PRIMARY_KEY AUTO_INCREMENT
	STRING_ (NONCE, 32)
	TIME_   (VALID)
END_TABLE

TABLE_(COMMITS)
	STRING_ (UID, 140)      UNIQUE NOT_NULL
	STRING_ (BRANCH, 512)
	STRING_ (CMT, 256)
	TIME_   (DT)
	STRING_ (AUTHOR, 200)
	STRING_ (MSG, 1024)
	STRING_ (PATH, 1024)
END_TABLE

TABLE_(RESULT)
	STRING_ (CMT_UID, 140)  INDEX
	INT_    (CLIENT_ID)     INDEX DUAL_UNIQUE(CMT_UID, CLIENT_ID)
	TIME_   (START)
	TIME_   (FINISHED)
	INT_    (STATUS)        NOT_NULL SQLDEFAULT(0)
	INT_    (OK)            NOT_NULL SQLDEFAULT(0)
	INT_    (ERR)           NOT_NULL SQLDEFAULT(0)
	INT_    (FAIL)          NOT_NULL SQLDEFAULT(0)
	INT_    (SKIP)          NOT_NULL SQLDEFAULT(0)
END_TABLE

TABLE_(MAIL)
	STRING_ (EMAIL, 1024)
	STRING_ (FILTER, 1024)
	STRING_ (TOKEN, 32)
	INT_    (UNIQ)          UNIQUE
	TIME_   (CTIME)
	BOOL_   (ACTIVE)        NOT_NULL SQLDEFAULT(0)
END_TABLE